### PR TITLE
DRILL-3993: Drill-specific changes in Calcite 1.15

### PR DESCRIPTION
**Pull request by vvysotskyi**
This pull request contains commits, cherry-picked from Apache Calcite master after 1.15 release and three commits, that should be reviewed:
- [CALCITE-2018] af04ef4
- [CALCITE-2087] 3990700
- Drill-specific changes: added a general class for Date/Time/Timestamp literals b4c43d4

### CODE REVIEW

**Review by chunhui-shi — COMMENTED** [review]
Why isn't this not an issue to Calcite itself? How does Calcite handle date and timestamp comparison? In postgres timestamp and date are comparable. Calcite should have worked as well.

**Comment by chunhui-shi** [comment]
While the Drill specific time/date change might be able to contribute back to calcite master, the change itself is fine. +1 LGTM.

**Comment by vvysotskyi** [comment]
@chunhui-shi, regarding date and timestamp comparison, Calcite strictly follows the SQL standard, but SQL spec does not allow to compare datetime types if they have different `<primary datetime field>`s (4.6 Datetimes and intervals). Therefore Calcite community won’t accept these changes.

**Comment by amansinha100** [comment]
@vvysotskyi the original PR for rebase on Calcite 1.13 also had a commit for AbstractConverter (Drill specific) in commit [1].  I did not see that in your PR for 1.15...any reason ? 

[1] https://github.com/mapr/incubator-calcite/pull/15/commits/837542cf3a5c392d1c82758b6b4e34f9424ab995

**Comment by vvysotskyi** [comment]
@amansinha100, I made some changes in Drill[1], so this commit is not needed anymore.

[1] https://github.com/apache/drill/commit/688e043b4546884d82422b266b419817d645acfc#diff-b1427a3d8838be9ba3690678740a27a5R32 (changes in Prel class)

**Comment by amansinha100** [comment]
Got it...good to know that the Drill side change (likely in conjunction with the changes for CALCITE-1148 for RelTrait conversion) obsoletes the need for [1] https://github.com/mapr/incubator-calcite/pull/15/commits/837542cf3a5c392d1c82758b6b4e34f9424ab995.

**Comment by amansinha100** [comment]
LGTM.  +1     Thanks @vvysotskyi and @KulykRoman for persisting with these changes.  The remaining 3 commits can be handled incrementally and are not blockers to move this forward. Let me know if you need help in deploying the new calcite build for use by Drill master branch.

**Pull request merged**
